# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "12pl9s809ka1lvp2nc76n9a36vjgw1nqjgd5k9gn836p4lm08aw8";
    x86_64-linux = "1w3ymzc5fydl0agb3fycvajxi621bya55lfv6kfvrfhp1bfg1n7q";
    armv7l-linux = "161nzhpyqqz2k4a1p363raxjvhgfp2mx2v3pa1lhj57084zn8s4l";
    aarch64-linux = "1zzs247rhgpzskmrac1lvxcplz064gqzpyg7an3zhiqw4yhkhslv";
    x86_64-darwin = "0gk7qmgpbvhvqvbis0932p45v2hblp84c78zr2r6cmp139c0bhmx";
    aarch64-darwin = "10sr29gzsv8dqj6a0dg54ws8avp8l8w5ll15filszwsixycfkp6j";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/wishlist/releases/download/v0.12.0/wishlist_0.12.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/wishlist/releases/download/v0.12.0/wishlist_0.12.0_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/wishlist/releases/download/v0.12.0/wishlist_0.12.0_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/wishlist/releases/download/v0.12.0/wishlist_0.12.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/wishlist/releases/download/v0.12.0/wishlist_0.12.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/wishlist/releases/download/v0.12.0/wishlist_0.12.0_Darwin_arm64.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "wishlist";
  version = "0.12.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./wishlist $out/bin/wishlist
    installManPage ./manpages/wishlist.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = with lib; {
    description = "The SSH directory";
    homepage = "https://charm.sh/";
    license = licenses.mit;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
