# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "1p9qdp3b8jy5sidbdqls9m6fldaka1cl5187k28z0zp1gl57n8v5";
    x86_64-linux = "07d5kpm8d6v7rf2giz7zx2sm95wki2crm3rayg3knx01x8n64aqr";
    armv7l-linux = "1b65ibh28y0s7ljk15hk4x0l1wgk154f7b357a7gkrgrmidgf169";
    aarch64-linux = "0vl4v72mnzlybws5myk2ihqy4037sq2jgzd8r1fa478ijwr2a10f";
    x86_64-darwin = "1d4c4kmd3cil1pf382d00h80r0mzz0wcr7ynsx0k6gqfnjjpis8s";
    aarch64-darwin = "0bkjf5y5pffgqb6nn02a3vmcajxijzpgh15wl9fb8axfkiga25pf";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/pop/releases/download/v0.1.0/pop_0.1.0_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/pop/releases/download/v0.1.0/pop_0.1.0_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/pop/releases/download/v0.1.0/pop_0.1.0_Linux_arm.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/pop/releases/download/v0.1.0/pop_0.1.0_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/pop/releases/download/v0.1.0/pop_0.1.0_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/pop/releases/download/v0.1.0/pop_0.1.0_Darwin_arm64.tar.gz";
  };
in pkgs.stdenv.mkDerivation {
  pname = "pop";
  version = "0.1.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pop $out/bin/pop
    installManPage ./manpages/pop.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = with lib; {
    description = "Send emails from your terminal. 📬";
    homepage = "https://charm.sh/";
    license = licenses.mit;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
