# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0ani5jpl4g7f3pv0pkccqqy4r9i5vapdkrpzrai8a9prgbbfjrji";
    x86_64-linux = "1m7vxnzk6dmxlxc2chy7vchd2n7vfk9ml2xi2n8yshvzavf60zc4";
    armv7l-linux = "0hc7h368v82vyfvvbyiknah9m9pzpmhbrw40s81zzhv354701r2v";
    aarch64-linux = "101vlzmzfa0lpgladqgc00yy3vi9zqqc1qmwzv7iilvmm406dgcl";
    x86_64-darwin = "1jjbn1f0ppzxh6srm14pg0mi3mf4860k797gh2lynhnfjplk7szl";
    aarch64-darwin = "04mhq42skr905csyq0g9ipc5n7qr75qangx8jdixdp51k113668j";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.3/crush_0.6.3_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.3/crush_0.6.3_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.3/crush_0.6.3_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.3/crush_0.6.3_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.6.3/crush_0.6.3_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.6.3/crush_0.6.3_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "crush_0.6.3_Linux_i386";
    x86_64-linux = "crush_0.6.3_Linux_x86_64";
    armv7l-linux = "crush_0.6.3_Linux_armv7";
    aarch64-linux = "crush_0.6.3_Linux_arm64";
    x86_64-darwin = "crush_0.6.3_Darwin_x86_64";
    aarch64-darwin = "crush_0.6.3_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crush";
  version = "0.6.3";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crush $out/bin/crush
    installManPage ./manpages/crush.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal.";
    homepage = "https://charm.sh/crush";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
