# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "03gakv3ww0rrg37jkqzd61mr7s7172nqah2gkb3hhc331vqv7hl9";
    x86_64-linux = "1rgp4lhalq6nq5c1a8pjf3d6pj72fhm77fkbvi0bnshzqsw9csch";
    armv7l-linux = "15xgs4lg9yggkln5i5qik710jj31fhadb9159ym7pib7fx6vpj8d";
    aarch64-linux = "0wfwwjk8x5ch1x4wg736pkhym5lyg17ffn1mgap3zax1hn6iiadb";
    x86_64-darwin = "0kg6ycrlzkdak8kwaar1hxk77mvskdhky7wc10gc73rjhmc53cn1";
    aarch64-darwin = "14rj6p29631jj2wqfd30ihdvlnkdiplfxaz8y4wrwdl1dvvywljx";
  };

  urlMap = {
    i686-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.1/crush_0.6.1_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.1/crush_0.6.1_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.1/crush_0.6.1_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/charmbracelet/crush/releases/download/v0.6.1/crush_0.6.1_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.6.1/crush_0.6.1_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/charmbracelet/crush/releases/download/v0.6.1/crush_0.6.1_Darwin_arm64.tar.gz";
  };
  sourceRootMap = {
    i686-linux = "crush_0.6.1_Linux_i386";
    x86_64-linux = "crush_0.6.1_Linux_x86_64";
    armv7l-linux = "crush_0.6.1_Linux_armv7";
    aarch64-linux = "crush_0.6.1_Linux_arm64";
    x86_64-darwin = "crush_0.6.1_Darwin_x86_64";
    aarch64-darwin = "crush_0.6.1_Darwin_arm64";
  };
in
stdenvNoCC.mkDerivation {
  pname = "crush";
  version = "0.6.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = sourceRootMap.${system};

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./crush $out/bin/crush
    installManPage ./manpages/crush.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "A powerful terminal-based AI assistant for developers, providing intelligent coding assistance directly in your terminal.";
    homepage = "https://charm.sh/crush";
    license = lib.licenses.fsl11Mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
